export const ADD_ARTICLE = `ADD_ARTICLE`;

const FOREGROUD_PRODUCT_SET_NAME = "FOREGROUND_PRODUCT_SET_NAME";
const FOREGROUD_PRODUCT_SET_CATEGORY = "FOREGROUND_PRODUCT_SET_CATEGORY";
const FOREGROUD_PRODUCT_SET_DESCRIPTION = "FOREGROUND_PRODUCT_SET_DESCRIPTION";
const FOREGROUD_PRODUCT_SET_GENDER = "FOREGROUND_PRODUCT_SET_GENDER";
const FOREGROUD_PRODUCT_SET_FRAME_MATERIAL = "FOREGROUND_PRODUCT_SET_FRAME_MATERIAL";
const FOREGROUD_PRODUCT_SET_SKU = "FOREGROUND_PRODUCT_SET_SKU";
const FOREGROUD_PRODUCT_SET_AVAILABLE = "FOREGROUND_PRODUCT_SET_AVAILABLE";
const FOREGROUD_PRODUCT_SET_IMAGES = "FOREGROUND_PRODUCT_SET_IMAGES";
const FOREGROUD_PRODUCT_SET_ID = "FOREGROUND_PRODUCT_SET_ID";

export const foreground_product_actions = {
    FOREGROUD_PRODUCT_SET_AVAILABLE,
    FOREGROUD_PRODUCT_SET_CATEGORY,
    FOREGROUD_PRODUCT_SET_DESCRIPTION,
    FOREGROUD_PRODUCT_SET_FRAME_MATERIAL,
    FOREGROUD_PRODUCT_SET_GENDER,
    FOREGROUD_PRODUCT_SET_ID,
    FOREGROUD_PRODUCT_SET_IMAGES,
    FOREGROUD_PRODUCT_SET_NAME,
    FOREGROUD_PRODUCT_SET_SKU
}
